version: '3.1'

services:

  nginx:
    build: docker/nginx
    container_name: s_nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./docker/nginx/logs:/var/log/nginx
    - ./htdocs:/var/www/htdocs
    depends_on:
    - phpfpm

  phpfpm:
    build: docker/phpfpm
    container_name: s_phpfpm
    volumes:
    - ./docker/phpfpm/conf.d:/usr/local/etc/php/conf.d
    - ./htdocs:/var/www/htdocs
  
